### ISSUE TITLE
FEATURE: Secondary Weapons

### ISSUE THREAD

**Issue by OcelotWalrus** [Dungeons-of-Kathallion/Dungeons-of-Kathallion#17]
Maybe we could add secondary weapons, which works like weapons but are intended to be small (like knifes, shields...). Their purpose will be only defense and they are optional. Maybe the secondary weapons could have `agility` stats?

Any suggestion?

**Comment by OcelotWalrus** [comment]
> Their purpose will be only defense and they are optional. Maybe the secondary weapons could have `agility` stats?

I think all weapons should have agility stats.

**Comment by OcelotWalrus** [comment]
What I propose is to make a new 'held slot' that is supposed to be the other hand to the player. Only small weapons like knife would be secondary weapons and shields. But the principal purpose of secondary weapons is defense but some of them like knifes could also have some damage stats.

**Comment by lumbar527** [comment]
**√** **lumbar527** approved these changes \<date\>

Yeah, I like that idea.

**Comment by lumbar527** [comment]
Reopening because the offhand is only implemented for shields.

**Comment by OcelotWalrus** [comment]
> Reopening because the offhand is only implemented for shields.

I can work on that if you want.

**Comment by lumbar527** [comment]
Sure!

**Comment by OcelotWalrus** [comment]
I dont think that Secondary Weapons are necessary and good to add.
This is no particular reason to add that.

**Comment by lumbar527** [comment]
I think having secondary weapons could be interesting, but for now I will close this.
