### ISSUE TITLE
Plot

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Dungeons-of-Kathallion#29]
**Is your feature request related to a problem? Please describe.**
There is no story.

**Describe the solution you'd like**
I want there to be a data file for plot stuff, like text when you get to a certain location. Also could be used with villages in #27 

**Describe alternatives you've considered**
N/A

**Additional context**
This is just a reminder for me to work on it, or a place to discuss features. I would like to be able to do the coding myself.

**Comment by OcelotWalrus** [comment]
I think I can add that with #27

**Comment by lumbar527** [comment]
I would prefer to be able to do it.

**Comment by OcelotWalrus** [comment]
Sure. My idea was to make a new data type that would be quests that are stored in `quests.yaml` and they would work like ES missions.

**Comment by lumbar527** [comment]
Partially resolved by 88554fc261cff9167320886e4a3211a6956a2301
