### ISSUE TITLE
BUG: colors.py typo

### ISSUE THREAD

**Issue by OcelotWalrus** [Dungeons-of-Kathallion/Dungeons-of-Kathallion#30]
So in the colors class, there is this typo:

![image](https://github.com/Dungeons-of-Kathallion/Dungeons-of-Kathallion/assets/87318892/3e3e953a-52f1-459b-be6e-25bb9c5f98ea)

The second `COLOR_BLACK` is supposed to be `COLOR_WHITE`

**Comment by lumbar527** [comment]
71390636828022eb6917673e4f90c243db05eef4
