### ISSUE TITLE
BUG: Plugin folder + Coordinate count key

### ISSUE THREAD

**Issue by OcelotWalrus** [Dungeons-of-Kathallion/Dungeons-of-Kathallion#31]
1.I saw you recently added the `plugin/` directory, like on Bane Of Wargs.
I didn't tested the code but when looking at it, I can already see the errors that would happen:
![image](https://github.com/Dungeons-of-Kathallion/Dungeons-of-Kathallion/assets/87318892/e807ae6d-52a8-435a-88d8-594dcad9dbf0)

When the game will look for the plugin path, it will load this path:
`<plugin name>plugin/item.yaml`
But it should be this instead:
`plugin/<plugin name>/item.yaml`

2.I recently made a commit in Bane Of Wargs so that you don't need the `coordinates count` key in the `map.yaml` file. Check this: https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/commit/7653880be655f1d4edaf19823c6c3166df215aed

**Comment by lumbar527** [comment]
7d5af20eaaa16f135621abebccbf33f8d32b0ac0 and da098fd1b84f6a4ccabdda6ed4056b60b7b97897. Thanks!
